/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type MemoryCategory = "digital_landmark" | "family_personal_life" | "foundational_milestone" | "joke_riddle_banter" | "relational_concept" | "scriptural_bedrock";

export type SimulationSpeaker = "clint" | "maica";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface SimulationMemories {
  createdAt: Generated<Timestamp>;
  description: string;
  keywords: Generated<string[]>;
  memoryCategory: MemoryCategory;
  memoryId: string;
  title: string;
}

export interface SimulationMessages {
  createdAt: Generated<Timestamp>;
  interactionId: string | null;
  messageId: string;
  sessionId: string;
  source: Generated<string>;
  speaker: SimulationSpeaker;
  text: string;
}

export interface SimulationSessions {
  activeEvent: string | null;
  activeMusic: string | null;
  clintInteractionId: string | null;
  clintMood: Generated<string>;
  createdAt: Generated<Timestamp>;
  currentActivity: Generated<string>;
  eventCooldowns: Generated<Json>;
  eventExpiresAt: Timestamp | null;
  maicaInteractionId: string | null;
  maicaMood: Generated<string>;
  sessionId: string;
  updatedAt: Generated<Timestamp>;
  world: Generated<string>;
}

export interface DB {
  simulationMemories: SimulationMemories;
  simulationMessages: SimulationMessages;
  simulationSessions: SimulationSessions;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const MemoryCategoryArrayValues: [MemoryCategory, ...MemoryCategory[]] = ["digital_landmark","family_personal_life","foundational_milestone","joke_riddle_banter","relational_concept","scriptural_bedrock"];
export const SimulationSpeakerArrayValues: [SimulationSpeaker, ...SimulationSpeaker[]] = ["clint","maica"];
// Table/column names whose snake_case spelling kysely's default CamelCasePlugin
// cannot recover from the camelCase name used in code (an underscore directly
// before a digit, e.g. reminder_48h_sent ⇄ reminder48hSent). The db helper's
// CamelCasePlugin subclass consults this map so those identifiers work in
// queries. Regenerated on every schema pull.
export const kyselyIdentifierOverrides: Record<string, string> = {};

// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.